endpoints:
  prometheus:

    enabled: true





management:
  metrics:
    export:
        prometheus:
          enabled: true
    enable:
      jvm: true
      root: true
    use-global-registry: true

  endpoints:
    prometheus:
      enabled: true



management:
  metrics:
    enable:
      jvm: true
      root: true
    use-global-registry: true
  endpoints:
    auditevents:
      enabled: true
    autoconfig:
      enabled: true
    beans:
      enabled: true
    configprops:
      enabled: true
    env:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
    endpoints:
      mappings:
        enabled: true
    status:
      enabled: true
    threaddump:
      enabled: true
    trace:
      enabled: true
    logfile:
      enabled: true
    web:
      include:
       include: prometheus,metrics,info,health
    enabled-by-default: true
    prometheus:
     jmx: true
     web: true

  endpoint:
    prometheus:
     cache:
       time-to-live: 1ms
     enabled: true # Whether to enable the prometheus endpoint.

#management:
#  endpoints:
#    web:
#      expose: *






#management:
#  metrics:
#    enable: true