management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus,httptrace,conditions

welcome:
  message: 'OcpMon Oliver'



logging:
  level:
    org.springframework.web: ERROR
    ch.oliverg: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"